### ISSUE TITLE
Mulighet for å legge til flere URL'er

### ISSUE THREAD

**Issue by frodehansen2** [navikt/accessibility-reporting-tool#7]
Vil det være mulig å legge til flere URL'er for en rapport? Vi har flere skjemaer som baserer seg på den samme grunnstrukturen, og tilgjengelighetsrapporten vil nok være lik for flere av dem

**Comment by Reasonable-Solutions** [comment]
No, that is a deliberate non-feature, even though we aren't explicit about it. 
Testing for this is based on "representative samples" and if you have several similar things, then sampling all of those is probably not really adding that much.
